name: numly
description: "Efficient cross-platform mental math training app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # language
  collection: ^1.19.0

  # ui
  gap: ^3.0.1
  material_symbols_icons: ^4.2815.0

  # state
  go_router: ^15.1.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^3.0.3

  # persistence
  drift: ^2.26.1
  drift_flutter: ^0.2.4

  # native
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.6

  # i18n
  intl: any
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0

dev_dependencies:
  # testing
  test: ^1.25.15
  flutter_test:
    sdk: flutter

  # build
  build_runner: ^2.7.1
  drift_dev: ^2.26.1

  # lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

  # command to generate the icons: `dart run flutter_launcher_icons`
  flutter_launcher_icons: ^0.14.3

  # commands to set the application name:
  # `dart run change_app_package_name:main app.numly.android --android`
  # `dart run change_app_package_name:main app.numly.ios --ios`
  change_app_package_name: ^1.5.0
  freezed: ^3.2.3


flutter:
  generate: true

flutter_launcher_icons:
  image_path: assets/logo/numly.png
  android: true
  web:
    generate: true

# command to generate the splash screen: `dart run flutter_native_splash:create`
flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: assets/logo/numly.png
  android_12:
    color: "#FFFFFF"
